### ISSUE TITLE
bug: `inline` option for embedfields doesn't do anything

### ISSUE THREAD

**Issue by jaydensar** [skyra-project/discord-components#114]
**Describe the bug**
setting an embed field as inline doesn't do anything, and it appears as though it isn't inline

**To Reproduce**
attempt to set an embed field as inline

**Expected behavior**
the field is properly inline

**Screenshots**
![](https://i.jaydensar.net/2021/08/DHOh1cyYHLT29O.png)

no difference between inline and non-inlinefields

**Comment by Favna** [comment]
Ah.. well that's actually only a problem on the example code not being properly representative of how to do inline fields. You're missing the `inline-index` property.

This will work:
```html
				<discord-messages>
					<discord-message profile="skyra">
						<discord-embed slot="embeds">
							<discord-embed-fields slot="fields">
								<discord-embed-field field-title="Inline field title" inline inline-index="1"> Some value here </discord-embed-field>
								<discord-embed-field field-title="Inline field title" inline inline-index="2"> Some value here </discord-embed-field>
								<discord-embed-field field-title="Inline field title" inline inline-index="3"> Some value here </discord-embed-field>
							</discord-embed-fields>
						</discord-embed>
					</discord-message>
				</discord-messages>
```

The reason you have to set the index manually is because there is simply no reliable way to determine which field goes where, because each `DiscordEmbedField` is distinct and doesn't have knowledge of how many there are in total to then divide that amount by 3.

**Comment by jaydensar** [comment]
Thanks, worked perfectly!
