### ISSUE TITLE
question: add CommonJS support

### ISSUE THREAD

**Issue by IceeMC** [skyra-project/discord-components#129]
Support CommonJS as some of my node_modules do not work with this.

**Comment by Favna** [comment]
There already is CommonJS support and when using `require` it will be loaded automatically because it's set as the `main` field in the package.json

https://unpkg.com/browse/@skyra/discord-components-core@2.10.0/dist/index.cjs.js
https://unpkg.com/browse/@skyra/discord-components-core@2.10.0/dist/cjs/index.cjs.js

---

That said however, this is a web library and when developing for the web you should always use something like Webpack / Snowpack / Parcel / Esbuild to bundle your code and they all use ESM style packages and imports so please do enlighten me to what bizarre environment you want to use this lib or what you're workflow is that you need CJS.

**Comment by IceeMC** [comment]
Because your react components do not work, and I refuse to switch to MJS.
```./node_modules/@skyra/discord-components-react/dist/index.mjs
Can't import the named export 'defineCustomElements' from non EcmaScript module (only default export is available)```

**Comment by Favna** [comment]
You do not use the `.mjs` file extension when writing React code. You use Webpack / Snowpack / Parcel / ESBuild to bundle your web code and you use ESM. Why? Because the web literally doesn't support Require. The web is 100% ESM. 

If you don't want to use ESM, that's your problem.

**Comment by IceeMC** [comment]
You’re so toxic, the fuck is your problem?

**Comment by IceeMC** [comment]
Oh, and i’ve been using react since early 2020, piss off you stupid idiot.

**Comment by Favna** [comment]
Oh, and i’ve been using react since early 2018, piss off.
