### ISSUE TITLE
bug: Empty Embed Descriptions get rendered

### ISSUE THREAD

**Issue by itohatweb** [skyra-project/discord-components#180]
**Describe the bug**
When creating a `discord-embed` with no description `discord-components` still adds a `discord-embed-description` div even though its empty. This messes with the design.

**To Reproduce**
1. Create an Embed
2. Don't add a description
3. Add a field
4. See the empty box above the field

**Expected behavior**
No div gets added when the description is empty

**Screenshots**
![image](https://user-images.githubusercontent.com/72305210/144876050-bad47a44-7a44-4f15-99fe-ee34572bdf65.png)

**Comment by favna** [comment]
What is the exact use case of ensuring this doesn't happen? The mentality I've had with this library is that you code all the HTML for what goes into the rendered result and so you can do emptyness checks yourself. Likewise this library also doesn't do any HTML / JS sanitation because it expects implementers to do that.

**Comment by favna** [comment]
Oh that's a missing if check I guess.

**Comment by favna** [comment]
Released in [v2.12.1](https://github.com/skyra-project/discord-components/releases/tag/v2.12.1)
