### ISSUE TITLE
request: Responsive elements

### ISSUE THREAD

**Issue by HunteRoi** [skyra-project/discord-components#190]
**Is your feature request related to a problem? Please describe.**

I am using your components on a project that has to be mobile-friendly. Unfortunately, some components such as DiscordInvite are not responsive. Their fixed width and height make it difficult to use in PWA aimed for mobiles.

**Describe the solution you'd like**

That your components' styles include media queries to make them fit smaller screens.

**Describe alternatives you've considered**

Making the CSS my own, but this is obviously not the goal of my project and thus the media queries regarding this should not be in my app source code.

**Additional context**

N/A

**Comment by favna** [comment]
Gee this will be a huge undertaking honestly because we take our CSS directly from the Discord client and their desktop client doesn't scale down to mobile size at all. Their android client doesn't use React Native and their iOS client cannot be harvested for CSS because of iOS restrictions (I think a jailbroken device theoretically can because [Harmony](https://repo.dynastic.co/package/com.revulate.harmony) tweak exists but I would have no idea what to do for that)

**Comment by favna** [comment]
I'm closing this as it's not feasible to do as per the above.
