### ISSUE TITLE
How to setup with VuePress v3

### ISSUE THREAD

**Issue by Default-01** [skyra-project/discord-components#237]
I don't know how to set up discord components for my VuePress documentation site. 

https://github.com/Default-01/SlickBot-Docs/blob/main/guide/.vuepress/clientAppEnhance.ts

Above is the project I'm working on, if anyone can help or show me how to use it I would be really thankful!

**Comment by favna** [comment]
I have no idea how Vuepress works but this project uses StencilJS so you can refer to https://stenciljs.com/docs/vue or join the StencilJS Slack. Supporting specific generators like vuepress is outside of the scope of this project because we already support Vue, Angular, React and anything else that allows custom components by the pure nature of using StencilJS.
